platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CrashlyticsRecorder_Tests' do
  pod 'CrashlyticsRecorder/Crashlytics', :path => '../'
  pod 'CrashlyticsRecorder/Answers', :path => '../'
  pod 'CrashlyticsRecorder/FirebaseAnalytics', :path => '../'

  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'

end
