platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CrashlyticsRecorder_Tests' do
  pod 'CrashlyticsRecorder', :path => '../'

  pod 'Fabric'
  pod 'Crashlytics'

end
