source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CrashlyticsRecorder_Tests', :exclusive => true do
  pod 'CrashlyticsRecorder', :path => '../'

  pod 'Fabric'
  pod 'Crashlytics'

end
